### ISSUE TITLE
when module.resource startsWith `delegated` and throw error

### ISSUE THREAD

**Issue by wszgrcy** [xz64/license-webpack-plugin#104]
In this position
![image](https://user-images.githubusercontent.com/9607121/128799993-442256c3-cc7f-4cab-bf04-ef0c16affd36.png)
If I add condition and skip ,can build success
![image](https://user-images.githubusercontent.com/9607121/128800111-caf30773-a60f-4848-adee-14dbec06554a.png)

When I use plugin as follow
```ts
  config.plugins!.push(
    new webpack.DllReferencePlugin({
      context: path.resolve(__dirname),
      manifest: require('./dist/manifest.json'),
    })
  );
```
error
```log
[error] HookWebpackError: ENOENT: no such file or directory, scandir
    at makeWebpackError (/Users/chen/my-project/abc/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/chen/my-project/abc/node_modules/webpack/lib/Compilation.js:2513:12
    at eval (eval at create (/Users/chen/my-project/abc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at fn (/Users/chen/my-project/abc/node_modules/webpack/lib/Compilation.js:452:17)
    at _next4 (eval at create (/Users/chen/my-project/abc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (/Users/chen/my-project/abc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:1)
    at fn (/Users/chen/my-project/abc/node_modules/webpack/lib/Compilation.js:464:9)
    at _next3 (eval at create (/Users/chen/my-project/abc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (/Users/chen/my-project/abc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:60:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- inner error --
Error: ENOENT: no such file or directory, scandir
    at Object.readdirSync (fs.js:1043:3)
    at CacheBackend.provideSync (/Users/chen/my-project/abc/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:233:32)
    at WebpackFileSystem.listPaths (/Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/WebpackFileSystem.js:78:24)
    at LicenseTextReader.readLicense (/Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/LicenseTextReader.js:37:54)
    at PluginChunkReadHandler.processModule (/Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/PluginChunkReadHandler.js:46:62)
    at /Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/PluginChunkReadHandler.js:22:23
    at WebpackModuleFileIterator.internalCallback (/Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/WebpackModuleFileIterator.js:25:13)
    at WebpackModuleFileIterator.iterateFiles (/Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/WebpackModuleFileIterator.js:10:9)
    at /Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/PluginChunkReadHandler.js:20:32
    at WebpackChunkModuleIterator.iterateModules (/Users/chen/my-project/abc/node_modules/license-webpack-plugin/dist/WebpackChunkModuleIterator.js:42:21)


```

**Comment by xz64** [comment]
Thanks for fixing it. published in v2.3.21
