### ISSUE TITLE
Problems with pnpm

### ISSUE THREAD

**Issue by binarious** [xz64/license-webpack-plugin#42]
When using the combination of Angular CLI and pnpm I get the following error:
```
LicenseWebpackPlugin(node:29173) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/myproj/node_modules/.registry.npmjs.org/package.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at LicenseExtractor.readPackageJson (/myproj/node_modules/.registry.npmjs.org/license-webpack-plugin/1.3.1/webpack-sources@1.1.0/node_modules/license-webpack-plugin/dist/LicenseExtractor.js:126:23)
```

The owner of pnpm [told me](https://github.com/pnpm/pnpm/issues/767#issuecomment-402837570), that this should this library should not preserve symlinks in order for it to work.

It would be great to get this working with pnpm.

**Comment by xz64** [comment]
I have put a fix in for the next major release (still in alpha state, version 2.0.0-alpha.5). You can install it using `license-webpack-plugin@next`
