### ISSUE TITLE
licenseTemplateDir errors on missing license

### ISSUE THREAD

**Issue by solgarius** [xz64/license-webpack-plugin#60]
I get the below error, crashing webpack when I use the `licenseTemplateDir` option and a license is missing from the directory. It should probably handle this case better and instead fallback to `handleMissingLicenseText` or simply report missing license text.

  ```
.\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:79
            finally { if (e_1) throw e_1.error; }
                               ^

Error: ENOENT: no such file or directory, open '.\buildConfig\licenseTemplates\BSD-3-Clause.txt'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Storage.provideSync (.\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:95:16)
    at CachedInputFileSystem.readFileSync (.\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:254:31)
    at WebpackFileSystem.readFileAsUtf8 (.\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:52:24)
    at LicenseTextReader.readLicense (.\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:42:18)
    at PluginChunkReadHandler.processModule (.\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:52:62)
    at .\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:29:23
    at WebpackModuleFileIterator.iterateFiles (.\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:7:9)
    at .\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:27:32
    at Array.forEach (<anonymous>)
    at WebpackChunkModuleIterator.iterateModules (.\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:36:27)
    at PluginChunkReadHandler.processChunk (.\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:26:29)
    at _loop_1 (.\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:48:37)
    at WebpackCompilerHandler.iterateChunks (.\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:71:17)
    at Compilation.<anonymous> (.\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:37:31)
    at Compilation.applyPluginsAsyncSeries (.\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (.\node_modules\webpack\lib\Compilation.js:635:10)
    at next (.\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (.\node_modules\webpack\lib\ProgressPlugin.js:113:6)
    at next (.\node_modules\tapable\lib\Tapable.js:204:14)
    at ExtractTextPlugin.<anonymous> (.\node_modules\extract-text-webpack-plugin\index.js:345:4)
    at Compilation.applyPluginsAsyncSeries (.\node_modules\tapable\lib\Tapable.js:206:13)
    at sealPart2 (.\node_modules\webpack\lib\Compilation.js:631:9)
    at next (.\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (.\node_modules\webpack\lib\ProgressPlugin.js:109:6)
    at next (.\node_modules\tapable\lib\Tapable.js:204:14)
    at ExtractTextPlugin.<anonymous> (.\node_modules\extract-text-webpack-plugin\index.js:317:5)
    at .\node_modules\async\dist\async.js:473:16
    at iteratorCallback (.\node_modules\async\dist\async.js:1064:13)
```

**Comment by xz64** [comment]
Thanks for reporting this. It is fixed in version 2.1.1
